# Generated by Django 4.0 on 2023-07-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_review_photo_review_name_alter_review_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='available',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='crossed_out_price',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='store.ProductAttribute', to='store.AttributeValue'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='crossed_out_price_modified',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.attributevalue'),
        ),
    ]
